"""
Member 3 — Blockchain Client
==============================
Updated to load ABI from the JSON file saved by deploy_contract.py.
No Hardhat or Node.js required.
"""

import os
import json
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

SEPOLIA_EXPLORER = "https://sepolia.etherscan.io/tx/"

# Load ABI from file generated by deploy_contract.py
# Falls back to hardcoded minimal ABI if file not found
ABI_PATH = Path("contracts/VideoForensicLedger_abi.json")

FALLBACK_ABI = [
    {
        "inputs": [
            {"internalType": "string", "name": "videoId", "type": "string"},
            {"internalType": "string", "name": "hash",    "type": "string"},
        ],
        "name": "storeHash",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "string", "name": "videoId", "type": "string"}],
        "name": "getHash",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "string", "name": "videoId", "type": "string"}],
        "name": "isRegistered",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
]


def load_abi():
    if ABI_PATH.exists():
        with open(ABI_PATH) as f:
            print(f"[BlockchainClient] Loaded ABI from {ABI_PATH}")
            return json.load(f)
    print("[BlockchainClient] ABI file not found — using fallback ABI")
    return FALLBACK_ABI


class BlockchainClient:

    def __init__(self):
        from web3 import Web3

        provider_url  = os.getenv("WEB3_PROVIDER_URL")
        private_key   = os.getenv("PRIVATE_KEY")
        contract_addr = os.getenv("CONTRACT_ADDRESS")

        if not all([provider_url, private_key, contract_addr]):
            raise EnvironmentError(
                "Missing .env values. "
                "Need: WEB3_PROVIDER_URL, PRIVATE_KEY, CONTRACT_ADDRESS"
            )

        self.w3 = Web3(Web3.HTTPProvider(provider_url))
        if not self.w3.is_connected():
            raise ConnectionError(f"Cannot connect to Ethereum node: {provider_url}")

        self.account      = self.w3.eth.account.from_key(private_key)
        self._private_key = private_key

        abi = load_abi()
        self.contract = self.w3.eth.contract(
            address=Web3.to_checksum_address(contract_addr),
            abi=abi,
        )

        balance_wei = self.w3.eth.get_balance(self.account.address)
        balance_eth = self.w3.from_wei(balance_wei, "ether")

        print(f"[BlockchainClient] Connected to Sepolia")
        print(f"[BlockchainClient] Wallet  : {self.account.address}")
        print(f"[BlockchainClient] Balance : {balance_eth:.4f} ETH")
        print(f"[BlockchainClient] Contract: {contract_addr}")

        if balance_eth < 0.001:
            raise ValueError(
                f"Wallet balance too low: {balance_eth} ETH. "
                "Get free test ETH from sepoliafaucet.com"
            )

    def store_hash(self, video_id: str, video_hash: str) -> dict:
        """Store SHA-256 hash on blockchain using EIP-1559 transaction."""
        nonce        = self.w3.eth.get_transaction_count(self.account.address)
        latest       = self.w3.eth.get_block("latest")
        base_fee     = latest.get("baseFeePerGas", self.w3.to_wei(1, "gwei"))
        max_priority = self.w3.to_wei(1, "gwei")
        max_fee      = (base_fee * 2) + max_priority

        try:
            estimated_gas = self.contract.functions.storeHash(
                video_id, video_hash
            ).estimate_gas({"from": self.account.address})
            gas_limit = int(estimated_gas * 1.2)
        except Exception:
            gas_limit = 150_000

        print(f"[BlockchainClient] Storing hash for video: {video_id}")
        print(f"[BlockchainClient] Gas limit: {gas_limit}")

        txn = self.contract.functions.storeHash(video_id, video_hash).build_transaction({
            "from":                 self.account.address,
            "nonce":                nonce,
            "gas":                  gas_limit,
            "maxFeePerGas":         max_fee,
            "maxPriorityFeePerGas": max_priority,
            "type":                 "0x2",
        })

        signed  = self.w3.eth.account.sign_transaction(txn, private_key=self._private_key)
        tx_hash = self.w3.eth.send_raw_transaction(signed.raw_transaction)

        print(f"[BlockchainClient] Tx sent: {tx_hash.hex()}")
        print(f"[BlockchainClient] Waiting for confirmation...")

        receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)

        if receipt["status"] != 1:
            raise RuntimeError(f"Transaction failed: {SEPOLIA_EXPLORER}{tx_hash.hex()}")

        print(f"[BlockchainClient] Confirmed in block {receipt['blockNumber']}")

        return {
            "tx_hash":      tx_hash.hex(),
            "block_number": receipt["blockNumber"],
            "explorer_url": SEPOLIA_EXPLORER + tx_hash.hex(),
        }

    def get_hash(self, video_id: str):
        """Read hash from blockchain — free, no gas."""
        stored = self.contract.functions.getHash(video_id).call()
        return stored if stored else None

    def is_registered(self, video_id: str) -> bool:
        return self.contract.functions.isRegistered(video_id).call()

    def get_balance(self) -> float:
        wei = self.w3.eth.get_balance(self.account.address)
        return float(self.w3.from_wei(wei, "ether"))
